name: honeywell_quiz_app
description: A simple quiz app for Honeywell.

publish_to: 'none' # Remove this line if you want to publish to pub.dev

environment:
 sdk: ">=2.12.0 <3.0.0"

dependencies:
 flutter:
   sdk: flutter

dev_dependencies:
 flutter_test:
   sdk: flutter

flutter:
 uses-material-design: true
